### PR TITLE
Fix code styles

### PR DESCRIPTION
**Pull request by mikeckennedy**
There are lots of PEP 8 violations and other items. Using this lib in our code will push those to us. This PR attempts to fix those.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
I believe I accidentally included "Adds missing methods: response.json() and response.raise_for_status()." in this PR then took it back out. So please merge this one before #2 if you accept both.

**Comment by slingamn** [comment]
I recommend adding `# flake8: noqa` to your vendored copy (I would consider adding that to the upstream file, actually).

**Comment by mikeckennedy** [comment]
Thanks. Does that actually prevent PyCharm and other tools which are not Flake8 from issuing warnings? Also, does that also mean you're not accepting the PR (which is fine, it's your repo), just curious on your thoughts.

**Comment by slingamn** [comment]
Ah yeah, sorry for the brief response earlier. I'm probably not going to take this entire PR because it's out of scope for mureq to conform to linters or style guides used by external projects. (For example, some projects might want mureq to pass [black](https://github.com/psf/black), but which version of black?)

I'm going to incorporate part of #2 (I haven't decided how much yet); I'll get back to you.

I am not really familiar with PyCharm, but from the looks of its [documentation](https://www.jetbrains.com/help/pycharm/disabling-and-enabling-inspections.html) it will not respect `# flake8: noqa`. If there is a concise metadata change that can silence all PyCharm warnings, I'm interested (similarly for other tools/frameworks).

**Comment by mikeckennedy** [comment]
Thanks for considering it. I want to be clear about the suggested PR:

This is NOT about supporting PyCharm. Your code has 50 or so [PEP 8](https://pep8.org/) warnings.

PEP 8 is a core part of Python since 2001. It just so happens tools other than Flake8 point out errors that are these violations, this included PyCharm.

It honestly makes your code look unprofessional and unpolished. If you don't take this PR, I would recommend you run Black on your entire project and then go from there.

Edit: I do totally understand this is your project, so take this advice or leave it. No pressure. I just want to make sure the goal was clear with the conversation here.

**Comment by mikeckennedy** [comment]
This PR also includes other fixes in this realm you might not put in the same bucket. For example, you're using Python 2 style string formatting, I upgraded them to Python 3.6 style f-strings. You had redundant tests in a couple of if statements and I simplified them. Just FYI.

**Comment by mikeckennedy** [comment]
Just to close this out. Here's what it looks like when opening this project in editors that report PEP 8 violations (see the squigglies and errors in the scroll bar:

Screen Shot 2022-01-26 at 8 53 00 AM

**Comment by slingamn** [comment]
You convinced me that mureq.py should not display any PEP8 warnings; I pulled that into #5.

Projects vendoring mureq should not vendor the tests (they are not designed to be run in a CI/CD system), so I'm exempting the tests from any PEP8 requirement.

**Comment by slingamn** [comment]
Most of this made it into #5; closing

**Comment by mikeckennedy** [comment]
Thanks @slingamn I appreciate that. :)

**Pull request closed without merging**
