### PR TITLE
Imports don't repeat, docs fixed

### PR DESCRIPTION
**Pull request by jammon**
I found this cool project through PythonBytes (https://pythonbytes.fm/episodes/show/268/wait-you-can-google-that).

Just one little thing: There is no need to test if json has been imported already. Imports always only happen once. Just to be sure I made a little test:

If you have a module `module.py`:
```python
print("module being imported")
```

and a test file:
```python
def f1():
    import module as m
    print("inside f1")

def f2():
    import module as m
    print("inside f2")

f1()
f2()
```

the output is:

    module being imported
    inside f1
    inside f2

And the readme needed updating :-)

### CODE REVIEW

**Comment by jammon** [comment]
One more thing: pytest gave me two failed tests:

    FAILED tests/test_integration.py::MureqIntegrationUnixSocketTestCase::test_unix_socket - OSError: [Errno 57] Socket is not connected
    FAILED tests/test_integration.py::MureqIntegrationPortTestCase::test_source_address - http.client.HTTPException: [Errno 49] Can't assign requested address

**Comment by slingamn** [comment]
This is kind of a stupid micro-optimization on my part:

```
>>> timeit.timeit('import json', setup='import json')
0.10225769702810794
>>> timeit.timeit('if a is None: import json', setup='import json; a = json')
0.05237433101865463
```

I will consider removing it and will definitely take your readme changes.

re. the test failures, are you running on MacOS?

**Comment by jammon** [comment]
Ok, so it's still a difference! But you are right, 0.1 vs. 0.05 µs is really a "micro"-optimization :-)

And yes, it's MacOS.

**Comment by slingamn** [comment]
I think I can only guarantee that the integration tests will run correctly on Linux (since I only have a Linux system to test with).

**Pull request merged**
